redis: 
  image: redis
  ports: 
    - 9001:6379
postgres:
  image: postgres
  volumes:
    - /data
  environment:
    POSTGRES_DB: thesis
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
  ports:
    - 5432:5432
onionhost_composed:
  image: onionhost
  command: npm start
  environment: 
    REDIS_URL: 'redis'
    POSTGRES_URL: 'postgres'
    NODE_ENV: 'development'
  links: 
    - redis
    - postgres
  ports: 
    - 7000:3000
