redis: 
  image: redis
  ports: 
    - 9001:6379
onionhost_composed:
  image: onionhost
  command: npm start
  environment: 
    REDIS_URL: 'redis'
    NODE_ENV: 'development'
  links: 
    - redis
  ports: 
    - 7000:3000
