redis: 
  image: fishboy/redis:latest
  ports: 
    - 9001:6379
  redisBanner:
    image: omnipotentOnions/redis-commander
    command: --redis-host redis
    links: 
      - redis:redis
    ports: 
      - 9002:8081
